from circulo import Circulo

circulo_uno = Circulo(1, 13)
circulo_dos = Circulo(2, 5)
circulo_tres = Circulo(3, 21)
circulo_cuatro = Circulo(4, 52)
circulo_cinco = Circulo(5, 231)

print("\n ------------------------------------ \n")
print("Circulo ", circulo_uno.id)
print("\n El área es: ", circulo_uno.calcular_area())
print("\n El perimetro es: ", circulo_uno.calcular_perimetro())
print("\n ------------------------------------ \n")
print("Circulo ", circulo_dos.id)
print("\n El área es: ", circulo_dos.calcular_area())
print("\n El perimetro es: ", circulo_dos.calcular_perimetro())
print("\n ------------------------------------ \n")
print("Circulo ", circulo_tres.id)
print("\n El área es: ", circulo_tres.calcular_area())
print("\n El perimetro es: ", circulo_tres.calcular_perimetro())
print("\n ------------------------------------ \n")
print("Circulo ", circulo_cuatro.id)
print("\n El área es: ", circulo_cuatro.calcular_area())
print("\n El perimetro es: ", circulo_cuatro.calcular_perimetro())
print("\n ------------------------------------ \n")
print("Circulo ", circulo_cinco.id)
print("\n El área es: ", circulo_cinco.calcular_area())
print("\n El perimetro es: ", circulo_cinco.calcular_perimetro())
print("\n ------------------------------------ \n")